#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

regex='^\-S[cyu]{1,3}'
if [[ $1 =~ $regex ]]; then
	regex='c'
	if [[ $1 =~ $regex ]]; then
		#echo 'apt-get clean'
		apt-get clean
	fi
	regex='y'
	if [[ $1 =~ $regex ]]; then
		#echo 'apt-get update'
		apt-get update
	fi
	regex='u'
	if [[ $1 =~ $regex ]]; then
		#echo 'aptitude safe-upgrade'
		aptitude safe-upgrade
	fi
fi

if [ $# -gt 1 ]; then
	command=''
	regex='^\-R[sc]{0,2}'
	if [[ $1 =~ $regex ]]; then
		regex='s'
		if [[ $1 =~ $regex ]]; then
			regex='c'
			if [[ $1 =~ $regex ]]; then
				command+='aptitude purge'
			else
				command+='aptitude remove'
			fi
		else
			command+='dpkg -r --force-depends'
		fi

	else
		regex='^\-[QS][si]'
		if [[ $1 =~ $regex ]]; then
			regex='^\-Qs'
			if [[ $1 =~ $regex ]]; then
				command+='dpkg -l | grep'
			else
				regex='^\-Qi'
				if [[ $1 =~ $regex ]]; then
					command+='dpkg -S'
				else
					regex='^\-Ss'
					if [[ $1 =~ $regex ]]; then
						command+='apt-cache search'
					fi
				fi
			fi
		else
			command+='aptitude install'
		fi
	fi
	# filenames
	count=0
	str=''
	for i in $@; do
		if [ $count -gt 0 ]; then
			str+=" "$i
		fi
		count=1
	done

	command+=" "$str
	$command
fi

