#!/bin/bash

command=''
root=1

regex='^\-S[cyu]{1,3}'
if [[ $1 =~ $regex ]]; then
	regex='c'
	if [[ $1 =~ $regex ]]; then
		command='apt-get clean'
	fi
	regex='y'
	if [[ $1 =~ $regex ]]; then
		if [[ -n "$command" ]]; then
			command+=' && '
		fi
		command+='apt-get update'
	fi
	regex='u'
	if [[ $1 =~ $regex ]]; then
		if [[ -n "$command" ]]; then
                        command+=' && '
                fi
		command+='apt-get upgrade'
	fi
fi

if [ $# -gt 1 ]; then
	command=""
	regex='^\-R[sc]{0,2}'
	if [[ $1 =~ $regex ]]; then
		regex='s'
		if [[ $1 =~ $regex ]]; then
			regex='c'
			if [[ $1 =~ $regex ]]; then
				command+='apt-get remove --purge'
			else
				command+='apt-get remove'
			fi
		else
			command+='dpkg -r --force-depends'
		fi

	else
		root=0
		regex='^\-[QS][si]'
		if [[ $1 =~ $regex ]]; then
			regex='^\-Qs'
			if [[ $1 =~ $regex ]]; then
				command+='dpkg -l | grep'
			else
				regex='^\-Qi'
				if [[ $1 =~ $regex ]]; then
					command+='dpkg -S'
				else
					regex='^\-Ss'
					if [[ $1 =~ $regex ]]; then
						command+='apt-cache search'
					fi
				fi
			fi
		else
			command+='apt-get install'
		fi
	fi
	# filenames
	count=0
	str=''
	for i in $@; do
		if [ $count -gt 0 ]; then
			str+=" "$i
		fi
		count=1
	done

	command+=" "$str
fi

user=`whoami`
if [ $user != "root" ] && [ $root == 1 ]; then
       	su root -c "${command}"
else
       	eval $command
fi

exit 0

